### ISSUE TITLE
Feature request: "natural" tree drop

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#1]
Spigot 1.14.4
TreeFeller 1.7 and previous

I have been unable to find a combination of configuration settings that will drop logs "naturally". I appreciate that complex trees present a problem for this issue, but I would really like the option to drop a tree more-or-less as a reflection of its standing shape, in the configured direction. So please consider this a feature request:

**log-behavior: NATURAL**
When not configured for RANDOM directional-fall-behavior (ie., when a direction is specified):
When configured for any non-BREAK log-behavior:
For each Y value above the cut (Ybase), move each log block Y-Ybase meters in the configured direction (up to a point prevented by solid blocks), modulo any random velocity, then apply gravity. Logs should be rotated to horizontal, and oriented away from the base. Leaves configured for any non-BREAK leaf-behavior should behave similarly, except that all logs should be placed first, followed by leaves.  For simplicity, AWAY, TOWARD, LEFT and RIGHT directional-fall-behavior options could transform to one of the two bounding N-E-S-W orientations, thereby keeping the felled logs in a straight line.

In the simplest case (a branchless tree on flat ground with random-fall-velocity:0), this will create a straight connected set of logs outward from the base. On more varied terrain, the result would conform to the terrain on the Y-axis.

Extra credit: In cases where some number of air blocks exist below Ybase along the flight path, gravity could be limited to Ybase-1, thereby allowing a felled tree to create a bridge over a river or chasm.

**Comment by SlimeDog** [comment]
Does "help wanted" mean that a PR would be welcomed?

**Comment by ThizThizzyDizzy** [comment]
"Help Wanted" means that I'm not exactly sure how to build this. Pull requests and more information are helpful, but not required.
Specifically, I'm not sure how to make this work for trees with roots (and leave-stump off), very large trees with many branches, etc.

**Comment by SlimeDog** [comment]
Some reflections:
- I have not experienced trees with roots. Vanilla trees do not have them. Which plugin(s) produce(s) them?
- In my limited understanding, roots would be located only below the tree base (however that is defined), so they would not be affected. IMO, TF should not apply to them, in the same way that it doesn't apply to tree logs above _max-height_.
- For _leave-stump:off_, I suggest that the stump just be removed, without adding to the felled log string. I suppose the stump logs could be dropped as items.
- Strictly speaking, the cut log(s) should not be added to the felled collection either; that is, if a tree consists of four logs, only three logs would be dropped.
- For complex trees, I think the algorithm cited above still applies: move each log block Y-Ybase meters in the configured direction (up to a point prevented by solid blocks), modulo any random velocity, then apply gravity. So branches will result in stacks of logs
- IMO, all dropped logs should be oriented 90deg from their standing orientation, wrt the base. So the main truck logs would be oriented horizontally, and the branches oriented as appropriate to their original orientation. This is an extra -- nice to have, not required.

**Comment by ThizThizzyDizzy** [comment]
Added in version 1.10
