### ISSUE TITLE
Effects: sawdust ?

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#10]
Spigot 1.15.1
TreeFeller 1.11

Server start-up returns:
```
[17:14:25] [Server thread/WARN]: [TreeFeller] Failed to load effects!
```
based on configuration
```
global-effects:
    - sawdust
```
Sawdust was legal (or ignored) in TreeFeller 1.10.4

Are the recognized effects documented somewhere?

**Comment by ThizThizzyDizzy** [comment]
All effects have to be defined under the `effects:` section of the config at the very end; There's no prebuilt effects.
It was probably ignored in 1.10.4
The "Failed to load effects!" is sent when the `effects:` section is anything other than a list (it's empty by default)

**Comment by SlimeDog** [comment]
Yep! Works as expected. Mea culpa.
