### ISSUE TITLE
McMMO error

### ISSUE THREAD

**Issue by Sckaletz** [ThizThizzyDizzy/tree-feller#100]
It appears the plugin is no longer compatible with newer McMMO versions.

Server version: Paper 1.21.1-131
Treefeller version:  1.24.1
McMMO version: 2.2.026

Error: https://pastebin.com/LVypX1aX

**Comment by ThizThizzyDizzy** [comment]
Looks related to #99

**Comment by Sckaletz** [comment]
Ok. So it's being fixed, I assume?

**Comment by ThizThizzyDizzy** [comment]
Fixed in v1.24.3
