### ISSUE TITLE
Error with McMMO

### ISSUE THREAD

**Issue by shilofax** [ThizThizzyDizzy/tree-feller#101]
Error: https://pastebin.com/iPrpsPDU

Server Version:

This server is running Paper version 1.21.3-66-master@afb5b13 (2024-11-27T14:30:21Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

Plugin Version: 1.24.2
McMMO version: 2.2.028

Error appears in console.

**Comment by ThizThizzyDizzy** [comment]
Duplicate of #100

**Comment by ThizThizzyDizzy** [comment]
Fixed in v1.24.3
