### ISSUE TITLE
Feature Request - end of tool life chat warning

### ISSUE THREAD

**Issue by martinambrus** [ThizThizzyDizzy/tree-feller#14]
If the player cannot use its tool to chop down an entire tree or mine out an entire vein, would it be possible to add a message into chat telling them so? Right now, I always think the plugin bugged out or that I'm lagging until I realize that everything works but my axe has last 2 uses left.

**Comment by ThizThizzyDizzy** [comment]
Perhaps this would work better as an actionbar notification (and sound), but that’s a good idea.

**Comment by ThizThizzyDizzy** [comment]
Added in 1.12
Example usage:
chat-durability-low: "Your Tool's almost broken! ({0}<{1})"
