### ISSUE TITLE
Feature request: Require entire cross-section to be cut

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#2]
Please implement the following as a configurable option:
- The entire cross-section of the trunk must be cut before the tree drops. For example, a jungle tree cross-section is 2x2. All four logs should be removed before the tree drops.

**Comment by ThizThizzyDizzy** [comment]
Partial fix added in 1.7.1; doesn't work reliably for trees larger than 2x2

**Comment by SlimeDog** [comment]
Nice! Confirmed working as expected in TF 1.7.1 on Spigot 1.14.4.

I have only vanilla and Essentials:bigtree trees, so it works great for me.

**Comment by ThizThizzyDizzy** [comment]
Closing this because, when combined with max-trunks, this now works for arbitrarily large tree trunks
