### ISSUE TITLE
Add support for Prism

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/tree-feller#22]

**Comment by ThizThizzyDizzy** [comment]
(I'm not sure how to access prism's API to log changed blocks)

**Comment by DevJake** [comment]
Hey there @ThizThizzyDizzy, is this still something in development? I use Prism frequently, so to have this plugin logged to it would be fantastic! No worries if not though

**Comment by ThizThizzyDizzy** [comment]
Ooh, thanks!
I'll look into it when I get back to working on treefeller again

**Comment by ThizThizzyDizzy** [comment]
Misclicked x.x
