### ISSUE TITLE
Trees Cutting part way. 

### ISSUE THREAD

**Issue by whisperer195** [ThizThizzyDizzy/tree-feller#24]
Hello! I am trying to get the plugin to work for custom trees. I've gotten it to work fine for most, however, these spruce trees are having strange issues where they seem to cut partway. I will include all the relevant files and a little video as an example. 

Config:
[config.zip](https://github.com/ThizThizzyDizzy/tree-feller/files/5744102/config.zip)

Logs/ debug info for trees:
https://pastebin.com/dA8SZZnV

Video Example:
https://youtu.be/So3crNrRDbQ

**Comment by ThizThizzyDizzy** [comment]
It looks like something's wrong with the trees themselves, but I can't tell from the video; Is it possible for me to look at the trees myself?

**Comment by whisperer195** [comment]
Yes! This was on my test server but I dropped the plugin on the public one.
Do you want to look at them there and see for yourself?

Also, not sure why but when I was testing on my private server I had trees
working but when I copied the config it seems some aren’t anymore... I’m
gonna double check the config to make sure my changes stayed. Do you want
my discord or somthing? Makes it easier to communicate than email.

**Comment by ThizThizzyDizzy** [comment]
Sure!

It's possible it could be interfering with another plugin; do the private & public servers have different plugins on them?

Here's a link to my discord server :)
https://discord.gg/dhcPSMt

**Comment by whisperer195** [comment]
It’s pretty much an exact copy, but I did take out discordSRV and a block
logging plugin.


This is my discord if if you wanna use that. Whisperer#8088
