### ISSUE TITLE
"FALL_HURT_BREAK" Drop incorrect amount of items compared to other behavior

### ISSUE THREAD

**Issue by Uboaaaaa** [ThizThizzyDizzy/tree-feller#25]
When behavior of logs and leaves are set to "FALL_HURT_BREAK", they drop significantly less amount of items compared to "FALL_BREAK" or simply "BREAK"

To reproduce:
1. add this tree
`- [[JUNGLE_LOG, JUNGLE_WOOD], JUNGLE_LEAVES, {sapling: JUNGLE_SAPLING, max-saplings: 4, log-behavior: FALL_HURT_BREAK, damage-mult: 1.0, directional-fall-velocity: 0.0, vertical-fall-velocity: 0.02, random-fall-velocity: 0.0, lock-fall-cardinal: false}]`
2. plant a 4x4 jungle log and fell it. You should find abnormally few logs being dropped on the ground.
3. change `FALL_HURT_BREAK` to `FALL_BREAK`
4. repeat 2, you should obtain a correct amount of logs.

**Comment by ThizThizzyDizzy** [comment]
Confirmed

**Comment by ThizThizzyDizzy** [comment]
Looks like this is actually another bug with bukkit; you can't spawn items too close to each other or some will be deleted.

**Comment by ThizThizzyDizzy** [comment]
Managed to work around it :D
