### ISSUE TITLE
Add stumps

### ISSUE THREAD

**Issue by Darutan92** [ThizThizzyDizzy/tree-feller#29]
Implement stumps. Only those blocks that are above the cut down are cut, and everything below and the cut down block itself remain. Thus, we get pretty realistic stumps, when even cutting down the lowest block near the ground, it will remain, and the player will need to sort of "uproot" the stump, cutting it down again if he wants to get everything from the tree to the last block. That is, there is still a need to check - if there is no other block of the same type above the block to be cut (it is the top), then it will drop, if there is, then only the higher one will be dropped.

**Comment by ThizThizzyDizzy** [comment]
Already implemented; see `leave-stump` in the config
If you want to fell the stump quickly, add another tree (after the existing one) with a decreased `required-logs` and `required-leaves`
