### ISSUE TITLE
Feature request: Smoke (or other) effect

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#3]
Please consider adding a configurable effect when a tree is felled. Smoke is nice. None should probably be the default.

**Comment by ThizThizzyDizzy** [comment]
Alright- I’ll list off a few effects- feel free to add as many as you want to this list

1. Particle effects
Any amount of any particle effect, with any settings
2. Sounds
Any sound at any pitch or volume
3. Explosions
...because why not?

**Comment by SlimeDog** [comment]
Nice.

**Comment by ThizThizzyDizzy** [comment]
Added in version 1.9
