### ISSUE TITLE
[Suggestion] Add Drop2Inventory API

### ISSUE THREAD

**Issue by mfnalex** [ThizThizzyDizzy/tree-feller#32]
Hi, I am the author of Drop2Inventory and Drop2Inventory Plus. The upcoming versions of D2I will have an API. It would be nice if you could support that.

You would have to shade the D2I API into the .jar file and call Drop2InventoryAPI.registerDrop() for every broken log before calling `World#dropItem` or `World#dropItemNaturally`. You can just call that method even if D2I isn't installed, in which case the method will just not do anything.

API information (Javadocs link is at the bottom): https://github.com/JEFF-Media-GbR/Drop2InventoryAPI

**Comment by ThizThizzyDizzy** [comment]
Added in v1.16
