### ISSUE TITLE
Tools: Required-Name not working

### ISSUE THREAD

**Issue by VimaMT** [ThizThizzyDizzy/tree-feller#38]
I have tried to set the tool's required-name in the config file manually. Regardless of what I do, it will not work for me. I'm trying to set it to &dAn Epic Axe.

I tried using /treefeller config while in game. I clicked upon the tool, then on required-name. I got a blank screen, and could not enter anything.

I'm using Paper 1.18.1 and the latest version of Thizzy's TreeFeller.

**Comment by ThizThizzyDizzy** [comment]
What did you input for `required-name`, and what is the name of the tool?
(to get the name of the tool, use the vanilla command `/data get entity @s SelectedItem.tag.display.Name`)

**Comment by ThizThizzyDizzy** [comment]
required-name is a String, not an array (you shouldn't have the `[]`)
for the last example, `required-name: Axe` should work. I'm unsure how chat colors are handled though (I do not do any special handling for them; In the config, try using `§` instead of `&`)

**Comment by VimaMT** [comment]
I got it to work with:

- {type: DIAMOND_AXE, required-enchantments: {durability: 3, dig_speed: 5}, required-lore: [&7This axe... it's awesome., &7It can chop down trees real fast.], required-name: An Epic Axe}

I was not able to make color codes work on it yet.

**Comment by ThizThizzyDizzy** [comment]
Nice, glad it worked! :D
I may add support for alternate color codes (aka &) in the future; `§` is the character minecraft used internally

**Comment by VimaMT** [comment]
Thank you for providing the plugin.
