### ISSUE TITLE
Sand is dropped when falling animation is enabled and tree falls on partial blocks.

### ISSUE THREAD

**Issue by mfcfbro** [ThizThizzyDizzy/tree-feller#49]
When any type of Fall_Break animation is enabled and the blocks fall over any partial block such as snow layers, plants, saplings, paths, etc, a sand block is dropped onto the ground. I have verified this is happening with 1.20.0 on the latest spigot, paper, and purpur server jars for 1.19.2.

**Comment by mfcfbro** [comment]
I just realized there was an update yesterday. The issue still occurs on version 1.20.1.

**Comment by ThizThizzyDizzy** [comment]
Unable to reproduce on craftbukkit and spigot 1.19.2; Can you verify that another plugin or datapack isn't interfering somehow?

**Comment by mfcfbro** [comment]
You are 100% correct. It's something in my config. Resetting all my configs fixed it but I have no idea what it was. If you care to know what it is I'll take some time to test, otherwise it's all fixed.

Thanks!
