### ISSUE TITLE
Feature request: world whitelist/blacklist

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#5]
The **worlds: key** is fine in many cases, but consider this use case: I generally want the tools to be available, except in one specific world (TreeFeller works poorly in initial skyblock worlds). So a general world whitelist/blacklist configuration option (either one or the other,but not both simultaneously) would be very useful.

**Comment by SlimeDog** [comment]
Trying to accomplish this with permissions
```
>perms group player permission check treefeller.iron_axe world_skyblock
[LuckPerms] player has permission treefeller.iron_axe set to false in context server=world_skyblock.
```
config.yml
```
tools:
    - { type: IRON_AXE, requiredPermissions: [treefeller.iron_axe] }
```

Nevertheless, I can use an iron_axe to fell a tree with TF activation. Not sure what I'm doing wrong.

**Comment by ThizThizzyDizzy** [comment]
Check the startup logs and /treefeller debug. Do they make references to the permission?

**Comment by SlimeDog** [comment]
Nothing in the start-up log. No mention of the permissions as I fell a tree.

**Comment by ThizThizzyDizzy** [comment]
Unable to reproduce issue with permissions; world blacklist option added in 1.9.5

**Comment by SlimeDog** [comment]
Blacklist works great. Thanks.
