### ISSUE TITLE
Option to remove decorations (snow, vines, etc)

### ISSUE THREAD

**Issue by Temyxxa** [ThizThizzyDizzy/tree-feller#64]
Blocks associated with a tree (snow fell on tree, creepers have grown) remain in the sky after felling a tree.
Is it possible to add the ability to update or delete these objects?

**Comment by ThizThizzyDizzy** [comment]
this is usually caused by questionable performance 'enhancements' on the side of the server software
Decoration removal (snow, vines, etc) is planned, but for a workaround you can try adding them to the tree leaves

**Comment by ThizThizzyDizzy** [comment]
- [ ] Snow
- [ ] Vines
- [ ] mangrove propagules
- [ ] cocoa beans
