### ISSUE TITLE
Mangrove floating blocks

### ISSUE THREAD

**Issue by BuilderDan** [ThizThizzyDizzy/tree-feller#65]
Breaking mangrove trees breaks everything, but then leaves floating vines, propagules and moss_carpet that do not decay. I turned off leaf-breaking but it still breaks the leaves of mangroves too

**Comment by ThizThizzyDizzy** [comment]
This is usually caused by the server software not respecting block updates; you can try adding the decorations to the tree's leaves, although it won't be perfect

> I turned off leaf-breaking but it still breaks the leaves of mangroves too

Did you set `leaf-break-range` to `0`?

**Comment by BuilderDan** [comment]
Yes, leaf-break-range was set to 0 and it still broke Mangrove leaves / hence leaving the floating blocks (that is why I set it to 0, to allow the natural leaf-decay to break the floaters, but then it still cut the leaves lol)

Where would I add them to the tree's leaves? Is this a specific part of the config that lists extra bits that associate with the tree type, like jungle having cocoa beans and vines?

**Comment by ThizThizzyDizzy** [comment]
Can you check for errors in the server console when you run `/treefeller reload`?
If it fails to load the config, it will use default values, which would ignore the leaf break range adjustment

As for the decorations, there is no special handling for that yet (#64)
A current workaround is to add the decorations to the tree's `leaves` so it will break them as if they were just more leaves. (You may also have to increase leaf-detect-range and leaf-break-range)

The problem with this is that it can extend beyond where you expect it to (for example, if you add snow, it may break snow on the ground if it is connected to the trunk)

**Comment by BuilderDan** [comment]
Ah, now that you mention it, snow on trees stays floating too

**Comment by BuilderDan** [comment]
Also, think it is important to note that FAWE says this in the console when cutting down a Mangrove or Spruce trees which I added  more decorations to, vines, propagules, moss_carpet, and then snow for spruce. 
![image](https://github.com/ThizThizzyDizzy/tree-feller/assets/19805371/c0f5c6c9-a34e-4199-a1f8-d5331a72889e)

**Comment by ThizThizzyDizzy** [comment]
oh, so it's FAWE that's stopping it
That "Physics lag" *is* the removal of the decorations

**Comment by ThizThizzyDizzy** [comment]
When TreeFeller destroys blocks, it triggers "physics updates" (also known as block updates)
This causes (among other things) blocks like snow, vines, torches, and any other block that requires support to break as well

This is all normal minecraft behavior, although plugins often disable this in the name of "performance"

it appears that FAWE is detecting a bunch of physics updates happening at once and canceling them, which causes the snow/vines/etc to stick around

**Comment by ThizThizzyDizzy** [comment]
The workaround makes the treefeller explicity remove those blocks as well, instead of leaving it to the physics updates
This actually causes even more physics updates, but fawe is cancelling all of them anyway

**Comment by ThizThizzyDizzy** [comment]
A couple more notes here:

> Yes, leaf-break-range was set to 0 and it still broke Mangrove leaves
I'm assuming you only changed the global value; In the default config, mangrove trees have this set to 16 override set to help take care of roots

Also, even with decoration removal, there still seems to occasionally be floating vines left behind; This appears to be just a quirk of the world generation though, as they can be found naturally like this
