### ISSUE TITLE
False Positive Virus

### ISSUE THREAD

**Issue by lf751** [ThizThizzyDizzy/tree-feller#72]
Latest release triggers a virus warning on windows defender.

**Comment by ThizThizzyDizzy** [comment]
Thats... interesting;
Where did you download it from?

**Comment by lf751** [comment]
SpigotMC

**Comment by ThizThizzyDizzy** [comment]
Very odd; even VirusTotal gives it an all clear;
I'll test it on windows in a bit

**Comment by ThizThizzyDizzy** [comment]
Tested on windows; (downloaded from spigot)
Didn't trip any warnings; even from manual scan

**Comment by lf751** [comment]
Sorry, updating virus definitions fixed it for me.
