### ISSUE TITLE
Tree Feller does not work with mcmmo classic

### ISSUE THREAD

**Issue by cloakfox** [ThizThizzyDizzy/tree-feller#9]
Error: https://pastebin.com/DLttqrRe

Using PaperSpigot 1.15.1
McMMO Classic 1.6.1 https://www.spigotmc.org/resources/official-mcmmo-classic.2445/

Tree Feller version 1.10.4

**Comment by ThizThizzyDizzy** [comment]
This is because McMMO lacks the getXpFromBlock method I use to add the XP

How much XP do you get for breaking a block of wood?

**Comment by cloakfox** [comment]
According to experience.yml

`    Woodcutting:
        Acacia: 90
        Birch: 90
        Dark_Oak: 90
        Generic: 70
        Jungle: 100
        Redwood: 80
        Huge_Mushroom_Red: 70
        Huge_Mushroom_Brown: 70
        Huge_Mushroom_2: 70
        Huge_Mushroom_1: 70
        Stripped_Spruce_Log: 80
        Stripped_Oak_Log: 70
        Spruce_Log: 80
        Stripped_Dark_Oak_Log: 90
        Stripped_Birch_Log: 90
        Acacia_Log: 90
        Oak_Log: 70
        Stripped_Acacia_Log: 90
        Birch_Log: 90
        Stripped_Jungle_Log: 100
        Jungle_Log: 100
        Dark_Oak_Log: 90
        Stripped_Jungle_Wood: 100
        Stripped_Acacia_Wood: 90
        Mushroom_Stem: 80
        Oak_Wood: 70
        Jungle_Wood: 70
        Dark_Oak_Wood: 70
        Spruce_Wood: 70
        Stripped_Oak_Wood: 70
        Stripped_Dark_Oak_Wood: 90
        Red_Mushroom_Block: 70
        Brown_Mushroom_Block: 70
        Acacia_Wood: 70
        Birch_Wood: 70
        Stripped_Birch_Wood: 90
        Stripped_Spruce_Wood: 80`


[experience.zip](https://github.com/ThizThizzyDizzy/tree-feller/files/4026489/experience.zip)

**Comment by ThizThizzyDizzy** [comment]
Added compatibility in v1.13.6
Sorry it took so long :P
