### ISSUE TITLE
1.20.5/6 support paper

### ISSUE THREAD

**Issue by Dr01000111** [ThizThizzyDizzy/tree-feller#92]
the plugin fails to load on paper mc

https://mclo.gs/dGfPOAH

Line 404

**Comment by ThizThizzyDizzy** [comment]
Looks specific to paper 1.20.5/6 due to NMS package changes
Looks like a simple fix, I'll patch it when I get home

**Comment by ThizThizzyDizzy** [comment]
Bug is fixed, but I'm gonna delay updating TreeFeller a liitle bit (tomorrow probably) to give AnvilGUI time to update (I'd have to update TreeFeller again anyway once that happens)

**Comment by Dr01000111** [comment]
could you maybe release a unstable version without the gui until anvil gui updates since it seems progress isnt being made on their github.

**Comment by WinterBeyond** [comment]
@ThizThizzyDizzy AnvilGUI has added support for 1.20.6 [https://github.com/WesJD/AnvilGUI/commit/038bf46c8b9092f112a207d77368fecd135051b5](https://github.com/WesJD/AnvilGUI/commit/038bf46c8b9092f112a207d77368fecd135051b5)

**Comment by ThizThizzyDizzy** [comment]
I saw it, planning on doing that tonight
Thanks for the poke :p

**Comment by ThizThizzyDizzy** [comment]
Updated vanillify/anvilgui and tested on craftbukkit-1.16.5, craftbukkit-1.19.4, craftbukkit-1.20.6, and paper-1.20.6-74.
Releasing v1.23.1 shortly
