### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by Chuckels745** [ThizThizzyDizzy/tree-feller#94]
This is a great plugin that I have been using for my servers that I would like to see get updated to 1.21!

**Comment by ThizThizzyDizzy** [comment]
waiting for WesJd/AnvilGUI#334

**Comment by Chuckels745** [comment]
Ok thanks for the quick response!

**Comment by ThizThizzyDizzy** [comment]
As a note, TreeFeller will mostly work fine on newer versions; the only parts that require updating for newer versions are AnvilGUI (used for some parts of the ingame configuration) and Vanillify (used for some things like actionbar messages.
